title: "Eric A. Chadwick"
email: "eachadwick@proton.me"
description: "Research-focused portfolio and CV."
baseurl: ""
url: ""
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
plugins:
  - jekyll-include-cache
exclude: ["README.md"]

collections:
  pages:
    output: true
    permalink: /:name/

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/

header:
  nav: navigation

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/

header:
  nav: navigation
