title: "Eric A. Chadwick"
email: "eachadwick@proton.me"
description: >-
  Research-focused portfolio and CV.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site
remote_theme: "mmistakes/minimal-mistakes@latest"
markdown: kramdown
plugins:
  - jekyll-include-cache
exclude: ["README.md"]

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/
  - title: "CV (PDF)"
    url: /assets/EricChadwick_CV_2025.pdf

header:
  nav: navigation
